// Code generated by mockery v2.42.1. DO NOT EDIT.

package service_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DispatchService is an autogenerated mock type for the DispatchService type
type DispatchService struct {
	mock.Mock
}

type DispatchService_Expecter struct {
	mock *mock.Mock
}

func (_m *DispatchService) EXPECT() *DispatchService_Expecter {
	return &DispatchService_Expecter{mock: &_m.Mock}
}

// SubscribeForDispatch provides a mock function with given fields: ctx, email, dispatch
func (_m *DispatchService) SubscribeForDispatch(ctx context.Context, email string, dispatch string) error {
	ret := _m.Called(ctx, email, dispatch)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeForDispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, dispatch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchService_SubscribeForDispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeForDispatch'
type DispatchService_SubscribeForDispatch_Call struct {
	*mock.Call
}

// SubscribeForDispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - dispatch string
func (_e *DispatchService_Expecter) SubscribeForDispatch(ctx interface{}, email interface{}, dispatch interface{}) *DispatchService_SubscribeForDispatch_Call {
	return &DispatchService_SubscribeForDispatch_Call{Call: _e.mock.On("SubscribeForDispatch", ctx, email, dispatch)}
}

func (_c *DispatchService_SubscribeForDispatch_Call) Run(run func(ctx context.Context, email string, dispatch string)) *DispatchService_SubscribeForDispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DispatchService_SubscribeForDispatch_Call) Return(_a0 error) *DispatchService_SubscribeForDispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DispatchService_SubscribeForDispatch_Call) RunAndReturn(run func(context.Context, string, string) error) *DispatchService_SubscribeForDispatch_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubscribeFromDispatch provides a mock function with given fields: ctx, email, dispatch
func (_m *DispatchService) UnsubscribeFromDispatch(ctx context.Context, email string, dispatch string) error {
	ret := _m.Called(ctx, email, dispatch)

	if len(ret) == 0 {
		panic("no return value specified for UnsubscribeFromDispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, dispatch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchService_UnsubscribeFromDispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeFromDispatch'
type DispatchService_UnsubscribeFromDispatch_Call struct {
	*mock.Call
}

// UnsubscribeFromDispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - dispatch string
func (_e *DispatchService_Expecter) UnsubscribeFromDispatch(ctx interface{}, email interface{}, dispatch interface{}) *DispatchService_UnsubscribeFromDispatch_Call {
	return &DispatchService_UnsubscribeFromDispatch_Call{Call: _e.mock.On("UnsubscribeFromDispatch", ctx, email, dispatch)}
}

func (_c *DispatchService_UnsubscribeFromDispatch_Call) Run(run func(ctx context.Context, email string, dispatch string)) *DispatchService_UnsubscribeFromDispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DispatchService_UnsubscribeFromDispatch_Call) Return(_a0 error) *DispatchService_UnsubscribeFromDispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DispatchService_UnsubscribeFromDispatch_Call) RunAndReturn(run func(context.Context, string, string) error) *DispatchService_UnsubscribeFromDispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewDispatchService creates a new instance of DispatchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DispatchService {
	mock := &DispatchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
