// Code generated by mockery v2.42.1. DO NOT EDIT.

package client_mocks

import (
	context "context"
	__ "subscription-api/pkg/grpc/currency_service"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyServiceClient is an autogenerated mock type for the CurrencyServiceClient type
type CurrencyServiceClient struct {
	mock.Mock
}

type CurrencyServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CurrencyServiceClient) EXPECT() *CurrencyServiceClient_Expecter {
	return &CurrencyServiceClient_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function with given fields: ctx, in, opts
func (_m *CurrencyServiceClient) Convert(ctx context.Context, in *__.ConvertRequest, opts ...grpc.CallOption) (*__.ConvertResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 *__.ConvertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *__.ConvertRequest, ...grpc.CallOption) (*__.ConvertResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *__.ConvertRequest, ...grpc.CallOption) *__.ConvertResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ConvertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *__.ConvertRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrencyServiceClient_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type CurrencyServiceClient_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - ctx context.Context
//   - in *__.ConvertRequest
//   - opts ...grpc.CallOption
func (_e *CurrencyServiceClient_Expecter) Convert(ctx interface{}, in interface{}, opts ...interface{}) *CurrencyServiceClient_Convert_Call {
	return &CurrencyServiceClient_Convert_Call{Call: _e.mock.On("Convert",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CurrencyServiceClient_Convert_Call) Run(run func(ctx context.Context, in *__.ConvertRequest, opts ...grpc.CallOption)) *CurrencyServiceClient_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*__.ConvertRequest), variadicArgs...)
	})
	return _c
}

func (_c *CurrencyServiceClient_Convert_Call) Return(_a0 *__.ConvertResponse, _a1 error) *CurrencyServiceClient_Convert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CurrencyServiceClient_Convert_Call) RunAndReturn(run func(context.Context, *__.ConvertRequest, ...grpc.CallOption) (*__.ConvertResponse, error)) *CurrencyServiceClient_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// NewCurrencyServiceClient creates a new instance of CurrencyServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyServiceClient {
	mock := &CurrencyServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
