// Code generated by mockery v2.42.1. DO NOT EDIT.

package repo_mocks

import (
	context "context"
	db "subscription-api/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, _a1, email
func (_m *UserRepo) CreateUser(ctx context.Context, _a1 db.DB, email string) error {
	ret := _m.Called(ctx, _a1, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DB, string) error); ok {
		r0 = rf(ctx, _a1, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 db.DB
//   - email string
func (_e *UserRepo_Expecter) CreateUser(ctx interface{}, _a1 interface{}, email interface{}) *UserRepo_CreateUser_Call {
	return &UserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, _a1, email)}
}

func (_c *UserRepo_CreateUser_Call) Run(run func(ctx context.Context, _a1 db.DB, email string)) *UserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.DB), args[2].(string))
	})
	return _c
}

func (_c *UserRepo_CreateUser_Call) Return(_a0 error) *UserRepo_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_CreateUser_Call) RunAndReturn(run func(context.Context, db.DB, string) error) *UserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
