with-expecter: true
outpkg: "{{.PackageName}}_mocks"
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
filename: "mock_{{ .InterfaceName | snakecase }}.go"

packages:
  subscription-api/internal/controllers:
    interfaces: 
      Context:
  subscription-api/internal/db:
    interfaces:
      DB:
        config:
          with-expecter: false
  subscription-api/internal/mailing:
    interfaces:
      Mailman:
  subscription-api/internal/services:
    interfaces:
      CurrencyService:
      DispatchService:
  subscription-api/internal/services/currency:
    interfaces:
      CurrencyAPIClient:
        with-expecter: false
        config:
          dir: "internal/mocks/clients"
          outpkg: "client_mocks"
  subscription-api/internal/services/dispatch:
    interfaces:
      UserRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
      SubRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
      DispatchRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
  subscription-api/pkg/grpc:
    interfaces:
      CurrencyServiceClient:
        config:
          dir: "internal/mocks/clients"
          outpkg: "client_mocks"
      DispatchServiceClient:
        config:
          dir: "internal/mocks/clients"
          outpkg: "client_mocks"
        


