with-expecter: true
outpkg: "{{.PackageName}}_mocks"
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"

packages:
  subscription-api/config:
    interfaces:
      Logger:
  subscription-api/internal/services:
    interfaces:
      CurrencyService:
      DispatchService:
  subscription-api/internal/services/currency:
    interfaces:
      CurrencyAPIClient:
        with-expecter: false
        config:
          dir: "internal/mocks/clients"
          outpkg: "client_mocks"
  subscription-api/internal/services/dispatch:
    interfaces:
      UserRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
      SubRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
      DispatchRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mocks"
  subscription-api/internal/db:
    interfaces:
      Store:
