with-expecter: true
outpkg: "{{.PackageName}}_mock"
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
filename: "mock_{{ .InterfaceName | snakecase }}.go"

packages:
  # subscription-api/internal/db:
  #   interfaces:
  #     DB:
  github.com/GenesisEducationKyiv/software-engineering-school-4-0-boredgus/service/dispatch/internal/service:
    interfaces:
      Mailman:
        config:
          dir: "internal/mocks/mailing"
          outpkg: "mailing_mock"
      UserRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mock"
      SubRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mock"
      DispatchRepo:
        config:
          dir: "internal/mocks/repo"
          outpkg: "repo_mock"
  github.com/GenesisEducationKyiv/software-engineering-school-4-0-boredgus/service/dispatch/internal/service/deps:
    interfaces:
      CurrencyServiceClient:
        config: 
          dir: "internal/mocks/client"
          outpkg: "client_mock"
    
  github.com/GenesisEducationKyiv/software-engineering-school-4-0-boredgus/service/dispatch/internal/grpc/server:
    interfaces:
      DispatchService:
        config: 
          dir: "internal/mocks/service"
          outpkg: "service_mock"



  # subscription-api/internal/services:
  #   interfaces:
  #     CurrencyService:
  #     DispatchService:
  # subscription-api/internal/services/currency:
  #   interfaces:
  #     CurrencyAPIClient:
  #       with-expecter: false
  #       config:
  #         dir: "internal/mocks/clients"
  #         outpkg: "client_mocks"
  # subscription-api/internal/services/dispatch:
  #   interfaces:
  #     UserRepo:
  #       config:
  #         dir: "internal/mocks/repo"
  #         outpkg: "repo_mocks"
  #     SubRepo:
  #       config:
  #         dir: "internal/mocks/repo"
  #         outpkg: "repo_mocks"
  #     DispatchRepo:
  #       config:
  #         dir: "internal/mocks/repo"
  #         outpkg: "repo_mocks"
  # subscription-api/pkg/grpc:
  #   interfaces:
  #     CurrencyServiceClient:
  #       config:
  #         dir: "internal/mocks/clients"
  #         outpkg: "client_mocks"
  #     DispatchServiceClient:
  #       config:
  #         dir: "internal/mocks/clients"
  #         outpkg: "client_mocks"
        


