// Code generated by mockery v2.42.1. DO NOT EDIT.

package mailing_mocks

import (
	mailing "subscription-api/internal/mailing"

	mock "github.com/stretchr/testify/mock"
)

// Mailman is an autogenerated mock type for the Mailman type
type Mailman struct {
	mock.Mock
}

type Mailman_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailman) EXPECT() *Mailman_Expecter {
	return &Mailman_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: e
func (_m *Mailman) Send(e mailing.Email) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mailing.Email) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailman_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Mailman_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - e mailing.Email
func (_e *Mailman_Expecter) Send(e interface{}) *Mailman_Send_Call {
	return &Mailman_Send_Call{Call: _e.mock.On("Send", e)}
}

func (_c *Mailman_Send_Call) Run(run func(e mailing.Email)) *Mailman_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mailing.Email))
	})
	return _c
}

func (_c *Mailman_Send_Call) Return(_a0 error) *Mailman_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailman_Send_Call) RunAndReturn(run func(mailing.Email) error) *Mailman_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailman creates a new instance of Mailman. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailman(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailman {
	mock := &Mailman{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
