name: CI
run-name: CI workflow by ${{ github.actor }}

on: 
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ['gateway','service/dispatch','service/currency','daemon/dispatch']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: ${{ matrix.modules }}
  
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ['gateway','service/dispatch','service/currency']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Go to module
        run: cd ${{ matrix.modules }}
      - name: Unit & integration tests 
        run: go test ./... -coverprofile="test-coverage.txt" -covermode count
      - name: Dependency tests
        run: |
          go install -v github.com/fdaines/arch-go@latest
          arch-go -v
  